# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style

# Disable frozen string literal comment requirement
# Ruby 3+ handles string freezing efficiently without the comment
Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: never
